# +----------------------------------------------------------------------------+ #
# |                        AuraSkills Shop Configuration                       | #
# |                                                                            | #
# |      Configure all shop pricing, sellable items, and buyable abilities    | #
# |             NEVER hard-code values - everything goes here!                 | #
# +----------------------------------------------------------------------------+ #

# Shop feature toggles
enabled: true
debug_mode: false

# Level Purchase Settings
level_purchase:
  enabled: true
  # Base cost for level 1
  base_cost: 100.0
  # Exponential multiplier (cost = base * multiplier ^ (level / 10))
  cost_multiplier: 1.5
  # Per-skill overrides (optional)
  skill_costs:
    farming: 80.0
    mining: 120.0
    # Add more skills as needed

# XP Purchase Settings (REMOVED - Use level purchase instead)
xp_purchase:
  enabled: false

# Item Selling System
sell_items:
  enabled: true
  # List of sellable items with their prices (RARE ITEMS ONLY)
  items:
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 1: Legendary Items (500-2000 coins)
    # ═══════════════════════════════════════════════════════════════════════
    DRAGON_EGG:
      enabled: true
      price: 2000.0
      display_name: "<light_purple>Dragon Egg"
      lore:
        - "<gray>The rarest trophy in existence"
        - "<yellow>Sells for: {price} coins"
    
    DRAGON_HEAD:
      enabled: true
      price: 800.0
      display_name: "<dark_purple>Dragon Head"
      lore:
        - "<gray>A fearsome decoration"
        - "<yellow>Sells for: {price} coins"
    
    NETHER_STAR:
      enabled: true
      price: 500.0
      display_name: "<white>Nether Star"
      lore:
        - "<gray>Dropped by the Wither boss"
        - "<yellow>Sells for: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 2: Epic Items (200-500 coins)
    # ═══════════════════════════════════════════════════════════════════════
    ELYTRA:
      enabled: true
      price: 400.0
      display_name: "<gray>Elytra"
      lore:
        - "<gray>Rare End wings for flight"
        - "<yellow>Sells for: {price} coins"
    
    NETHERITE_INGOT:
      enabled: true
      price: 250.0
      display_name: "<dark_red>Netherite Ingot"
      lore:
        - "<gray>The strongest material"
        - "<yellow>Sells for: {price} coins"
    
    BEACON:
      enabled: true
      price: 300.0
      display_name: "<white>Beacon"
      lore:
        - "<gray>Grants powerful buffs"
        - "<yellow>Sells for: {price} coins"
    
    TOTEM_OF_UNDYING:
      enabled: true
      price: 350.0
      display_name: "<gold>Totem of Undying"
      lore:
        - "<gray>Grants a second chance at life"
        - "<yellow>Sells for: {price} coins"
    
    HEART_OF_THE_SEA:
      enabled: true
      price: 200.0
      display_name: "<aqua>Heart of the Sea"
      lore:
        - "<gray>Powers the conduit"
        - "<yellow>Sells for: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 3: Rare Items (100-200 coins)
    # ═══════════════════════════════════════════════════════════════════════
    ANCIENT_DEBRIS:
      enabled: true
      price: 180.0
      display_name: "<dark_purple>Ancient Debris"
      lore:
        - "<gray>Rare nether ore"
        - "<yellow>Sells for: {price} coins"
    
    TRIDENT:
      enabled: true
      price: 150.0
      display_name: "<aqua>Trident"
      lore:
        - "<gray>Rare drowned weapon"
        - "<yellow>Sells for: {price} coins"
    
    WITHER_SKELETON_SKULL:
      enabled: true
      price: 120.0
      display_name: "<dark_gray>Wither Skeleton Skull"
      lore:
        - "<gray>Needed to summon the Wither"
        - "<yellow>Sells for: {price} coins"
    
    SKELETON_SKULL:
      enabled: true
      price: 40.0
      display_name: "<white>Skeleton Skull"
      lore:
        - "<gray>Rare mob drop"
        - "<yellow>Sells for: {price} coins"
    
    ZOMBIE_HEAD:
      enabled: true
      price: 40.0
      display_name: "<green>Zombie Head"
      lore:
        - "<gray>Rare mob drop"
        - "<yellow>Sells for: {price} coins"
    
    CREEPER_HEAD:
      enabled: true
      price: 40.0
      display_name: "<green>Creeper Head"
      lore:
        - "<gray>Rare mob drop"
        - "<yellow>Sells for: {price} coins"
    
    SPONGE:
      enabled: true
      price: 100.0
      display_name: "<yellow>Sponge"
      lore:
        - "<gray>Found in ocean monuments"
        - "<yellow>Sells for: {price} coins"
    
    NAUTILUS_SHELL:
      enabled: true
      price: 120.0
      display_name: "<blue>Nautilus Shell"
      lore:
        - "<gray>Rare ocean treasure"
        - "<yellow>Sells for: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 4: Valuable Items (50-100 coins)
    # ═══════════════════════════════════════════════════════════════════════
    EMERALD:
      enabled: true
      price: 80.0
      display_name: "<green>Emerald"
      lore:
        - "<gray>Rare trading gem"
        - "<yellow>Sells for: {price} coins"
    
    DIAMOND:
      enabled: true
      price: 60.0
      display_name: "<aqua>Diamond"
      lore:
        - "<gray>Precious gem"
        - "<yellow>Sells for: {price} coins"
    
    SHULKER_SHELL:
      enabled: true
      price: 90.0
      display_name: "<purple>Shulker Shell"
      lore:
        - "<gray>Dropped by shulkers in the End"
        - "<yellow>Sells for: {price} coins"
    
    SHULKER_BOX:
      enabled: true
      price: 100.0
      display_name: "<purple>Shulker Box"
      lore:
        - "<gray>Portable storage solution"
        - "<yellow>Sells for: {price} coins"
    
    GHAST_TEAR:
      enabled: true
      price: 70.0
      display_name: "<white>Ghast Tear"
      lore:
        - "<gray>Rare nether drop"
        - "<yellow>Sells for: {price} coins"
    
    ENDER_PEARL:
      enabled: true
      price: 50.0
      display_name: "<dark_purple>Ender Pearl"
      lore:
        - "<gray>Teleportation item"
        - "<yellow>Sells for: {price} coins"
    
    BLAZE_ROD:
      enabled: true
      price: 60.0
      display_name: "<gold>Blaze Rod"
      lore:
        - "<gray>Essential nether resource"
        - "<yellow>Sells for: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 5: Special Items (25-50 coins)
    # ═══════════════════════════════════════════════════════════════════════
    ENCHANTED_GOLDEN_APPLE:
      enabled: true
      price: 150.0
      display_name: "<gold>Enchanted Golden Apple"
      lore:
        - "<gray>Extremely rare god apple"
        - "<yellow>Sells for: {price} coins"
    
    MUSIC_DISC_5:
      enabled: true
      price: 100.0
      display_name: "<aqua>Music Disc (5)"
      lore:
        - "<gray>Rare ancient city disc"
        - "<yellow>Sells for: {price} coins"
    
    MUSIC_DISC_PIGSTEP:
      enabled: true
      price: 80.0
      display_name: "<red>Music Disc (Pigstep)"
      lore:
        - "<gray>Rare bastion disc"
        - "<yellow>Sells for: {price} coins"
    
    ECHO_SHARD:
      enabled: true
      price: 90.0
      display_name: "<dark_aqua>Echo Shard"
      lore:
        - "<gray>Found in ancient cities"
        - "<yellow>Sells for: {price} coins"
    
    NETHERITE_SCRAP:
      enabled: true
      price: 65.0
      display_name: "<dark_red>Netherite Scrap"
      lore:
        - "<gray>Refined from ancient debris"
        - "<yellow>Sells for: {price} coins"
    
    PRISMARINE_CRYSTALS:
      enabled: true
      price: 40.0
      display_name: "<aqua>Prismarine Crystals"
      lore:
        - "<gray>Guardian drop"
        - "<yellow>Sells for: {price} coins"
    
    PRISMARINE_SHARD:
      enabled: true
      price: 30.0
      display_name: "<blue>Prismarine Shard"
      lore:
        - "<gray>Guardian drop"
        - "<yellow>Sells for: {price} coins"
    
    RABBIT_FOOT:
      enabled: true
      price: 45.0
      display_name: "<white>Rabbit's Foot"
      lore:
        - "<gray>Lucky rare drop"
        - "<yellow>Sells for: {price} coins"

# Buyable Abilities System
# These are SPECIAL abilities that must be purchased, separate from leveling
buyable_abilities:
  enabled: true
  
  # List of abilities that can be purchased
  # Format: ability_id -> cost and requirements
  abilities:
    # Farming - Growth Aura (powerful AOE effect)
    growth_aura:
      cost: 5000.0
      skill_requirement:
        farming: 50
      display_name: "<green>Growth Aura"
      description:
        - "<gray>Crops within 5 blocks grow faster"
        - "<gray>A powerful farming enhancement"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Farming Level 50"
        - "  <gray>• 5000 Skill Coins"
    
    # Foraging - Shredder (chance-based enhancement)
    shredder:
      cost: 4000.0
      skill_requirement:
        foraging: 40
      display_name: "<red>Shredder"
      description:
        - "<gray>Chance to deal 3x durability damage"
        - "<gray>Destroy tools faster for more XP"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Foraging Level 40"
        - "  <gray>• 4000 Skill Coins"
    
    # Fighting - Bleed (combat advantage)
    bleed:
      cost: 6000.0
      skill_requirement:
        fighting: 60
      display_name: "<dark_red>Bleed"
      description:
        - "<gray>Chance to make enemies bleed"
        - "<gray>Powerful in extended combat"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Fighting Level 60"
        - "  <gray>• 6000 Skill Coins"
    
    # Agility - Thunder Fall (rare ability)
    thunder_fall:
      cost: 7000.0
      skill_requirement:
        agility: 70
      display_name: "<yellow>Thunder Fall"
      description:
        - "<gray>Strike like lightning from above"
        - "<gray>Deal massive fall damage to enemies"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Agility Level 70"
        - "  <gray>• 7000 Skill Coins"
    
    # Alchemy - Lingering (advanced brewing)
    lingering:
      cost: 5500.0
      skill_requirement:
        alchemy: 55
      display_name: "<pink>Lingering"
      description:
        - "<gray>Brew lingering potions"
        - "<gray>Master alchemist ability"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Alchemy Level 55"
        - "  <gray>• 5500 Skill Coins"
    
    # Healing - Revival (ultimate ability)
    revival:
      cost: 10000.0
      skill_requirement:
        healing: 80
      display_name: "<light_purple>Revival"
      description:
        - "<gray>Chance to revive on death"
        - "<gray>The ultimate survival ability"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Healing Level 80"
        - "  <gray>• 10000 Skill Coins"

# Balance Settings
balance:
  # Maximum transaction amount per purchase
  max_transaction: 100000.0
  # Minimum balance warning threshold
  low_balance_warning: 100.0
  # Enable transaction logging
  log_transactions: true

# Display Settings
display:
  # Number format for prices
  price_format: "%.0f"
  # Currency symbol/name
  currency_name: "Skill Coins"
  currency_symbol: "⛁"
  # Show balance in menu title
  show_balance_in_title: true
