# +----------------------------------------------------------------------------+ #
# |                        AuraSkills Shop Configuration                       | #
# |                                                                            | #
# |      Configure all shop pricing, sellable items, and buyable abilities    | #
# |             NEVER hard-code values - everything goes here!                 | #
# +----------------------------------------------------------------------------+ #

# Shop feature toggles
enabled: true
debug_mode: false

# Level Purchase Settings
level_purchase:
  enabled: true
  # Base cost for level 1
  base_cost: 100.0
  # Exponential multiplier (cost = base * multiplier ^ (level / 10))
  cost_multiplier: 1.5
  # Per-skill overrides (optional)
  skill_costs:
    farming: 80.0
    mining: 120.0
    # Add more skills as needed

# XP Purchase Settings (REMOVED - Use level purchase instead)
xp_purchase:
  enabled: false

# Level Rewards (SkillCoins earned when leveling up)
level_rewards:
  enabled: true
  # Base reward for level 1
  base_reward: 50.0
  # Exponential multiplier (reward = base * multiplier ^ (level / 10))
  reward_multiplier: 1.2
  # Show coins reward in level up messages
  display_in_level_up: true
  # Per-skill overrides (optional)
  skill_rewards:
    farming: 40.0
    mining: 60.0
    # Add more skills as needed

# Item Selling System
sell_items:
  enabled: true
  # Global cooldown for all items (seconds) - prevents spam selling
  global_cooldown: 300  # 5 minutes
  # List of sellable items with their prices (RARE ITEMS ONLY)
  items:
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 1: Legendary Items (500-2000 coins)
    # ═══════════════════════════════════════════════════════════════════════
    DRAGON_EGG:
      enabled: true
      price: 2000.0
      cooldown: 3600  # 1 hour - very rare
      display_name: "<light_purple>Dragon Egg"
      lore:
        - "<gray>The rarest trophy in existence"
        - "<yellow>Sells for: {price} coins"
    
    DRAGON_HEAD:
      enabled: true
      price: 800.0
      cooldown: 1800  # 30 minutes
      display_name: "<dark_purple>Dragon Head"
      lore:
        - "<gray>A fearsome decoration"
        - "<yellow>Sells for: {price} coins"
    
    NETHER_STAR:
      enabled: true
      price: 500.0
      cooldown: 600  # 10 minutes
      display_name: "<white>Nether Star"
      lore:
        - "<gray>Dropped by the Wither boss"
        - "<yellow>Sells for: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 2: Epic Items (200-500 coins)
    # ═══════════════════════════════════════════════════════════════════════
    ELYTRA:
      enabled: true
      price: 400.0
      display_name: "<gray>Elytra"
      lore:
        - "<gray>Rare End wings for flight"
        - "<yellow>Sells for: {price} coins"
    
    NETHERITE_INGOT:
      enabled: true
      price: 250.0
      display_name: "<dark_red>Netherite Ingot"
      lore:
        - "<gray>The strongest material"
        - "<yellow>Sells for: {price} coins"
    
    BEACON:
      enabled: true
      price: 300.0
      display_name: "<white>Beacon"
      lore:
        - "<gray>Grants powerful buffs"
        - "<yellow>Sells for: {price} coins"
    
    TOTEM_OF_UNDYING:
      enabled: true
      price: 350.0
      display_name: "<gold>Totem of Undying"
      lore:
        - "<gray>Grants a second chance at life"
        - "<yellow>Sells for: {price} coins"
    
    HEART_OF_THE_SEA:
      enabled: true
      price: 200.0
      display_name: "<aqua>Heart of the Sea"
      lore:
        - "<gray>Powers the conduit"
        - "<yellow>Sells for: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 3: Rare Items (100-200 coins)
    # ═══════════════════════════════════════════════════════════════════════
    ANCIENT_DEBRIS:
      enabled: true
      price: 180.0
      display_name: "<dark_purple>Ancient Debris"
      lore:
        - "<gray>Rare nether ore"
        - "<yellow>Sells for: {price} coins"
    
    TRIDENT:
      enabled: true
      price: 150.0
      display_name: "<aqua>Trident"
      lore:
        - "<gray>Rare drowned weapon"
        - "<yellow>Sells for: {price} coins"
    
    WITHER_SKELETON_SKULL:
      enabled: true
      price: 120.0
      display_name: "<dark_gray>Wither Skeleton Skull"
      lore:
        - "<gray>Needed to summon the Wither"
        - "<yellow>Sells for: {price} coins"
    
    SKELETON_SKULL:
      enabled: true
      price: 40.0
      display_name: "<white>Skeleton Skull"
      lore:
        - "<gray>Rare mob drop"
        - "<yellow>Sells for: {price} coins"
    
    ZOMBIE_HEAD:
      enabled: true
      price: 40.0
      display_name: "<green>Zombie Head"
      lore:
        - "<gray>Rare mob drop"
        - "<yellow>Sells for: {price} coins"
    
    CREEPER_HEAD:
      enabled: true
      price: 40.0
      display_name: "<green>Creeper Head"
      lore:
        - "<gray>Rare mob drop"
        - "<yellow>Sells for: {price} coins"
    
    SPONGE:
      enabled: true
      price: 100.0
      display_name: "<yellow>Sponge"
      lore:
        - "<gray>Found in ocean monuments"
        - "<yellow>Sells for: {price} coins"
    
    NAUTILUS_SHELL:
      enabled: true
      price: 120.0
      display_name: "<blue>Nautilus Shell"
      lore:
        - "<gray>Rare ocean treasure"
        - "<yellow>Sells for: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 4: Valuable Items (50-100 coins)
    # ═══════════════════════════════════════════════════════════════════════
    EMERALD:
      enabled: true
      price: 80.0
      display_name: "<green>Emerald"
      lore:
        - "<gray>Rare trading gem"
        - "<yellow>Sells for: {price} coins"
    
    DIAMOND:
      enabled: true
      price: 60.0
      display_name: "<aqua>Diamond"
      lore:
        - "<gray>Precious gem"
        - "<yellow>Sells for: {price} coins"
    
    SHULKER_SHELL:
      enabled: true
      price: 90.0
      display_name: "<purple>Shulker Shell"
      lore:
        - "<gray>Dropped by shulkers in the End"
        - "<yellow>Sells for: {price} coins"
    
    SHULKER_BOX:
      enabled: true
      price: 100.0
      display_name: "<purple>Shulker Box"
      lore:
        - "<gray>Portable storage solution"
        - "<yellow>Sells for: {price} coins"
    
    GHAST_TEAR:
      enabled: true
      price: 70.0
      display_name: "<white>Ghast Tear"
      lore:
        - "<gray>Rare nether drop"
        - "<yellow>Sells for: {price} coins"
    
    ENDER_PEARL:
      enabled: true
      price: 50.0
      display_name: "<dark_purple>Ender Pearl"
      lore:
        - "<gray>Teleportation item"
        - "<yellow>Sells for: {price} coins"
    
    BLAZE_ROD:
      enabled: true
      price: 60.0
      display_name: "<gold>Blaze Rod"
      lore:
        - "<gray>Essential nether resource"
        - "<yellow>Sells for: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 5: Special Items (25-50 coins)
    # ═══════════════════════════════════════════════════════════════════════
    ENCHANTED_GOLDEN_APPLE:
      enabled: true
      price: 150.0
      display_name: "<gold>Enchanted Golden Apple"
      lore:
        - "<gray>Extremely rare god apple"
        - "<yellow>Sells for: {price} coins"
    
    MUSIC_DISC_5:
      enabled: true
      price: 100.0
      display_name: "<aqua>Music Disc (5)"
      lore:
        - "<gray>Rare ancient city disc"
        - "<yellow>Sells for: {price} coins"
    
    MUSIC_DISC_PIGSTEP:
      enabled: true
      price: 80.0
      display_name: "<red>Music Disc (Pigstep)"
      lore:
        - "<gray>Rare bastion disc"
        - "<yellow>Sells for: {price} coins"
    
    ECHO_SHARD:
      enabled: true
      price: 90.0
      display_name: "<dark_aqua>Echo Shard"
      lore:
        - "<gray>Found in ancient cities"
        - "<yellow>Sells for: {price} coins"
    
    NETHERITE_SCRAP:
      enabled: true
      price: 65.0
      display_name: "<dark_red>Netherite Scrap"
      lore:
        - "<gray>Refined from ancient debris"
        - "<yellow>Sells for: {price} coins"
    
    PRISMARINE_CRYSTALS:
      enabled: true
      price: 40.0
      display_name: "<aqua>Prismarine Crystals"
      lore:
        - "<gray>Guardian drop"
        - "<yellow>Sells for: {price} coins"
    
    PRISMARINE_SHARD:
      enabled: true
      price: 30.0
      display_name: "<blue>Prismarine Shard"
      lore:
        - "<gray>Guardian drop"
        - "<yellow>Sells for: {price} coins"
    
    RABBIT_FOOT:
      enabled: true
      price: 45.0
      display_name: "<white>Rabbit's Foot"
      lore:
        - "<gray>Lucky rare drop"
        - "<yellow>Sells for: {price} coins"

# Item Buying System (Shop Market)
buy_items:
  enabled: true
  # Allow players to buy rare items with SkillCoins
  # Buy prices are typically 2-3x higher than sell prices
  items:
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 1: Legendary Items
    # ═══════════════════════════════════════════════════════════════════════
    DRAGON_EGG:
      enabled: false  # Too rare to sell
      price: 5000.0
      stock: -1  # -1 = unlimited, >0 = limited stock per server restart
      display_name: "<light_purple>Dragon Egg"
      lore:
        - "<gray>The rarest trophy in existence"
        - "<yellow>Costs: {price} coins"
    
    NETHER_STAR:
      enabled: true
      price: 1500.0
      stock: -1
      display_name: "<white>Nether Star"
      lore:
        - "<gray>Used to craft beacons"
        - "<yellow>Costs: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 2: Epic Items
    # ═══════════════════════════════════════════════════════════════════════
    ELYTRA:
      enabled: true
      price: 1200.0
      stock: -1
      display_name: "<gray>Elytra"
      lore:
        - "<gray>Rare End wings for flight"
        - "<yellow>Costs: {price} coins"
    
    NETHERITE_INGOT:
      enabled: true
      price: 750.0
      stock: -1
      display_name: "<dark_red>Netherite Ingot"
      lore:
        - "<gray>The strongest material"
        - "<yellow>Costs: {price} coins"
    
    TOTEM_OF_UNDYING:
      enabled: true
      price: 1000.0
      stock: -1
      display_name: "<gold>Totem of Undying"
      lore:
        - "<gray>Grants a second chance at life"
        - "<yellow>Costs: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 3: Rare Items
    # ═══════════════════════════════════════════════════════════════════════
    ANCIENT_DEBRIS:
      enabled: true
      price: 500.0
      stock: -1
      display_name: "<dark_purple>Ancient Debris"
      lore:
        - "<gray>Rare nether ore"
        - "<yellow>Costs: {price} coins"
    
    TRIDENT:
      enabled: true
      price: 450.0
      stock: -1
      display_name: "<aqua>Trident"
      lore:
        - "<gray>Rare drowned weapon"
        - "<yellow>Costs: {price} coins"
    
    WITHER_SKELETON_SKULL:
      enabled: true
      price: 350.0
      stock: -1
      display_name: "<dark_gray>Wither Skeleton Skull"
      lore:
        - "<gray>Needed to summon the Wither"
        - "<yellow>Costs: {price} coins"
    
    SPONGE:
      enabled: true
      price: 300.0
      stock: -1
      display_name: "<yellow>Sponge"
      lore:
        - "<gray>Found in ocean monuments"
        - "<yellow>Costs: {price} coins"
    
    # ═══════════════════════════════════════════════════════════════════════
    # TIER 4: Valuable Items
    # ═══════════════════════════════════════════════════════════════════════
    EMERALD:
      enabled: true
      price: 200.0
      stock: -1
      display_name: "<green>Emerald"
      lore:
        - "<gray>Trading gem"
        - "<yellow>Costs: {price} coins"
    
    DIAMOND:
      enabled: true
      price: 150.0
      stock: -1
      display_name: "<aqua>Diamond"
      lore:
        - "<gray>Precious gem"
        - "<yellow>Costs: {price} coins"
    
    SHULKER_SHELL:
      enabled: true
      price: 250.0
      stock: -1
      display_name: "<purple>Shulker Shell"
      lore:
        - "<gray>Craft shulker boxes"
        - "<yellow>Costs: {price} coins"
    
    GHAST_TEAR:
      enabled: true
      price: 180.0
      stock: -1
      display_name: "<white>Ghast Tear"
      lore:
        - "<gray>Rare nether drop"
        - "<yellow>Costs: {price} coins"
    
    BLAZE_ROD:
      enabled: true
      price: 150.0
      stock: -1
      display_name: "<gold>Blaze Rod"
      lore:
        - "<gray>Essential nether resource"
        - "<yellow>Costs: {price} coins"
    
    ENDER_PEARL:
      enabled: true
      price: 120.0
      stock: -1
      display_name: "<dark_purple>Ender Pearl"
      lore:
        - "<gray>Teleportation item"
        - "<yellow>Costs: {price} coins"

# Buyable Abilities System
# These are SPECIAL abilities that must be purchased, separate from leveling
buyable_abilities:
  enabled: true
  
  # List of abilities that can be purchased
  # Format: ability_key -> cost and requirements
  abilities:
    # Farming - Growth Aura (powerful AOE effect) - Level 25 requirement
    auraskills/growth_aura:
      cost: 3000.0
      skill_requirement: auraskills/farming
      required_level: 25
      display_name: "<green>Growth Aura"
      description:
        - "<gray>Crops within 30 blocks grow faster"
        - "<gray>A powerful farming enhancement"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Farming Level 25"
        - "  <gray>• 3000 Skill Coins"
    
    # Mining - Hardened Armor (defensive boost) - Level 30 requirement  
    auraskills/hardened_armor:
      cost: 4000.0
      skill_requirement: auraskills/mining
      required_level: 30
      display_name: "<blue>Hardened Armor"
      description:
        - "<gray>Reduced damage while mining"
        - "<gray>Essential for deep excavations"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Mining Level 30"
        - "  <gray>• 4000 Skill Coins"
    
    # Fighting - Bleed (combat advantage) - Level 35 requirement
    auraskills/bleed:
      cost: 5000.0
      skill_requirement: auraskills/fighting
      required_level: 35
      display_name: "<dark_red>Bleed"
      description:
        - "<gray>Chance to make enemies bleed"
        - "<gray>Powerful in extended combat"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Fighting Level 35"
        - "  <gray>• 5000 Skill Coins"
    
    # Archery - Stun (crowd control) - Level 30 requirement
    auraskills/stun:
      cost: 3500.0
      skill_requirement: auraskills/archery
      required_level: 30
      display_name: "<yellow>Stun"
      description:
        - "<gray>Chance to stun enemies with arrows"
        - "<gray>Powerful crowd control ability"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Archery Level 30"
        - "  <gray>• 3500 Skill Coins"
    
    # Fishing - Epic Catch (rare loot) - Level 40 requirement
    auraskills/epic_catch:
      cost: 6000.0
      skill_requirement: auraskills/fishing
      required_level: 40
      display_name: "<aqua>Epic Catch"
      description:
        - "<gray>Chance to catch epic treasures"
        - "<gray>Legendary fishing ability"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Fishing Level 40"
        - "  <gray>• 6000 Skill Coins"
    
    # Defense - No Debuff (immunity) - Level 45 requirement
    auraskills/no_debuff:
      cost: 7000.0
      skill_requirement: auraskills/defense
      required_level: 45
      display_name: "<light_purple>No Debuff"
      description:
        - "<gray>Immunity to negative effects"
        - "<gray>Ultimate defensive ability"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Defense Level 45"
        - "  <gray>• 7000 Skill Coins"
    
    # Excavation - Lucky Spades (treasure finding) - Level 35 requirement
    auraskills/lucky_spades:
      cost: 4500.0
      skill_requirement: auraskills/excavation
      required_level: 35
      display_name: "<gold>Lucky Spades"
      description:
        - "<gray>Chance to find rare treasures"
        - "<gray>While digging with spades"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Excavation Level 35"
        - "  <gray>• 4500 Skill Coins"
    
    # Enchanting - Lucky Table (enhancement boost) - Level 50 requirement
    auraskills/lucky_table:
      cost: 8000.0
      skill_requirement: auraskills/enchanting
      required_level: 50
      display_name: "<purple>Lucky Table"
      description:
        - "<gray>Better enchantment outcomes"
        - "<gray>Master enchanter ability"
        - ""
        - "<yellow>Requirements:"
        - "  <gray>• Enchanting Level 50"
        - "  <gray>• 8000 Skill Coins"

# Balance Settings
balance:
  # Maximum transaction amount per purchase
  max_transaction: 100000.0
  # Minimum balance warning threshold
  low_balance_warning: 100.0
  # Enable transaction logging
  log_transactions: true

# Display Settings
display:
  # Number format for prices
  price_format: "%.0f"
  # Currency symbol/name
  currency_name: "Skill Coins"
  currency_symbol: "⛁"
  # Show balance in menu title
  show_balance_in_title: true
